# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"a\n\x07\x43\x61rData\x12\r\n\x05speed\x18\x01 \x01(\x05\x12\x0b\n\x03rpm\x18\x02 \x01(\x05\x12\x0c\n\x04gear\x18\x03 \x01(\x05\x12\x10\n\x08throttle\x18\x04 \x01(\x01\x12\r\n\x05\x62rake\x18\x05 \x01(\x01\x12\x0b\n\x03\x64rs\x18\x06 \x01(\x08\";\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0e\n\x06status\x18\x04 \x01(\t\"r\n\x0c\x44riverUpdate\x12\x15\n\rdriver_number\x18\x01 \x01(\t\x12$\n\x08\x63\x61r_data\x18\x02 \x01(\x0b\x32\x12.telemetry.CarData\x12%\n\x08position\x18\x03 \x01(\x0b\x32\x13.telemetry.Position\"M\n\x0eTelemetryBatch\x12(\n\x07\x64rivers\x18\x01 \x03(\x0b\x32\x17.telemetry.DriverUpdate\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\x0f\n\rStreamRequest2\\\n\x10TelemetryService\x12H\n\x0fStreamTelemetry\x12\x18.telemetry.StreamRequest\x1a\x19.telemetry.TelemetryBatch0\x01\x42@Z>github.com/peri-Bot/f1-telemetry-backend/proto/gen/telemetrypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/peri-Bot/f1-telemetry-backend/proto/gen/telemetrypb'
  _globals['_CARDATA']._serialized_start=30
  _globals['_CARDATA']._serialized_end=127
  _globals['_POSITION']._serialized_start=129
  _globals['_POSITION']._serialized_end=188
  _globals['_DRIVERUPDATE']._serialized_start=190
  _globals['_DRIVERUPDATE']._serialized_end=304
  _globals['_TELEMETRYBATCH']._serialized_start=306
  _globals['_TELEMETRYBATCH']._serialized_end=383
  _globals['_STREAMREQUEST']._serialized_start=385
  _globals['_STREAMREQUEST']._serialized_end=400
  _globals['_TELEMETRYSERVICE']._serialized_start=402
  _globals['_TELEMETRYSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
